# Generated by Django 3.2.8 on 2021-10-22 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sublease.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('listed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_bed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of beds in the whole unit')),
                ('num_bath', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of baths in the whole unit')),
                ('gender_preference', models.IntegerField(choices=[(0, 'No Preference'), (1, 'Male Only'), (2, 'Female Only')], default=0, verbose_name='gender preference')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_per_month', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('num_tenants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of tenants')),
                ('fees', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Applicable fees on the sublease')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.address')),
                ('amenities', models.ManyToManyField(blank=True, to='sublease.Amenity')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sublease.models.get_file_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublease.studentlisting')),
            ],
        ),
    ]
